[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.3.2"

[context.deploy-preview]
  command = "yarn build-preview"

[[redirects]]
  from = "/giftcards/*"
  to = "https://squareup.com/gift/DDKHCR6JQ7FHX/order"